ACTIVATION: relu
BATCH: 100
DATAFRAC: 1.0
DATAPATH: wet-dataset.npz
DECAYRATE: 0.5
EPOCHS: 600
FLOW: maf
FLOWLAYERS: 2
GPU: true
LR: 0.001
MAXPATIENCE: 50
MINLR: 0.0001
NNDEPTH: 3
NNWIDTH: 64
PERMUTATION: reversed
TRANS: affine
TRANSSTEP: 25
chi2_pval: 0.15454944135139892
fit_random_seed: 359542301909
kst_pval: 0.1832838125708538
model_random_seed: 897574554031
