ACTIVATION: relu
BATCH: 100
DATAFRAC: 1.0
DATAPATH: lhcb-dataset.npz
DECAYRATE: 0.5
EPOCHS: 600
FLOW: maf
FLOWLAYERS: 8
GPU: true
INTERVAL:
  - 4.0
KNOTS: 6
LR: 0.001
MAXPATIENCE: 50
MINLR: 1.0e-08
NNDEPTH: 2
NNWIDTH: 64
PERMUTATION: reversed
TRANS: rqs
TRANSSTEP: 25
chi2_pval: 0.7988875667061021
fit_random_seed: 97204239863
kst_pval: 0.10011031070024068
model_random_seed: 62572755187
