ACTIVATION: relu
BATCH: 100
DATAFRAC: 0.2990332256
DATAPATH: atlas-dataset.npz
DECAYRATE: 0.5
EPOCHS: 600
FLOWLAYERS: 8
GPU: true
INTERVAL:
  - 1.0e-06
  - 1.0
KNOTS: 12
LR: 0.01
MAXPATIENCE: 50
MINLR: 1.0e-06
NNDEPTH: 1
NNWIDTH: 512
PERMUTATION: random
TRANS: rqs
TRANSSTEP: 25
